[tool.poetry]
name = "fx-bayesian"
version = "0.1.0"
description = ""
authors = ["lennardong <lennard.ong@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.1.1"
pandas = "^2.2.2"
mypy = "^1.11.2"
pandas-datareader = "^0.10.0"
seaborn = "^0.13.2"
ipython = "^8.27.0"
ipykernel = "^6.29.5"
duckdb = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
